### ISSUE TITLE
Can Notifs be used in the Admin Interface?

### ISSUE THREAD

**Issue by Timtech4u** [danidee10/django-notifs#1]
Hi Danidee, I'll love to implement a custom notification into my admin interface, I think this can work :+1:

**Comment by danidee10** [comment]
Right now, The main focus is on In-app notifications Not the Admin interface. But this is something that can easily be done (Overriding the admin templates and using the `Notification` model).

But i'll definitely keep this feature in mind

**Comment by Timtech4u** [comment]
Thanks, that's exactly what I'll do since I'm using a custom Admin App. Great Job!
