### ISSUE TITLE
Can't find app named ogamechanic?

### ISSUE THREAD

**Issue by Timtech4u** [danidee10/django-notifs#2]
Hi Danidee, I couldn't get the ogamechanic app from pip, how did u installed yours?

**Comment by danidee10** [comment]
Woaaah!....This Repo is for a project I'm building. It's still in beta (or anything worse than beta). I'm still decoupling the app from the main project. It's not ready for public consumption yet (I haven't even documented it yet).

But thanks for reporting this. I'll fix it in my next commit

If you'll like to help out with the project (ideas/code) don't hesitate. Thanks! :smile:

**Comment by danidee10** [comment]
@Timtech4u this issue has been close in https://github.com/danidee10/django-notifs/commit/66556379e5707293747019ab591e6f057fddf72d

**Comment by danidee10** [comment]
@Timtech4u `django-notifs` is finally ready for public use with all the documentation you need to get started :smile: 

I also wrote a tutorial on how you can use it in conjunction with RabbitMQ to build a Realtime Chat application on my blog https://danidee10.github.io/2018/01/01/realtime-django-1.html

**Comment by Timtech4u** [comment]
@danidee10 really cool , I'll explore and share. Thanks
