### ISSUE TITLE
Support for DjangoChannels

### ISSUE THREAD

**Issue by hendrikschneider** [danidee10/django-notifs#22]
Hey, 
it would be awesome if this library could also offer the possibility to user django channels and redis for websocket connections.

Is there any chance for support?

**Comment by danidee10** [comment]
Hi, @hendrikschneider I'm afraid there's no chance for support now. (I don't have the time) but I would be willing to add it If a third-party decides to Implement it

**Comment by hendrikschneider** [comment]
I am interested in this feature and would also be interested in helping out. However, I won't have time this month. Would you mind to keep this issue open?

**Comment by danidee10** [comment]
Alright I will keep it open, when you're ready, let me know. :)

**Comment by danidee10** [comment]
it took a while but django-notifs finally has support for WebSockets via django-channels (The old uWSGI websocket has been removed)

There are other new changes:
- Support for multiple delivery backends (Celery, [rq](https://python-rq.org/), and [django-channels workers](https://channels.readthedocs.io/en/stable/topics/worker.html)!
- Automatic retries (for some backends) and a lot of internal improvements.

please check out the latest [docs](https://django-notifs.readthedocs.io/en/latest/) and don't hesitate to ask questions/raise issues.

closing this now.
