### ISSUE TITLE
Where is the code for RabbitMQ queue for each user based on username?

### ISSUE THREAD

**Issue by dsifat** [danidee10/django-notifs#24]
https://github.com/danidee10/django-notifs#how-to-listen-to-notifications
You have mentioned here...
"At the backend, A Rabbitmq queue is created for each user based on the username, so when you're connecting to the websocket server you have to pass the username in the websocket url"
I want to see that code. Can you help me to provide that link of code?

**Comment by danidee10** [comment]
Here: https://github.com/danidee10/django-notifs/blob/master/notifications/channels.py#L72-L78
