### ISSUE TITLE
Improve JSONField

### ISSUE THREAD

**Issue by danidee10** [danidee10/django-notifs#28]
We should take advantage of Postgres' native `JSONField` and enable it for Postgres users.

Other databases should fallback to the current Implementation.

**Comment by Natureshadow** [comment]
I propose doing a new major release and dropping support for Django < 3.1 instead. Django 3.1 introduced a generic JSONField that uses the backend-specific field if available, and a fallback if not.

**Comment by danidee10** [comment]
That's great! (I wasn't aware of the new JSONField).

I wouldn't drop support for Django < 3.1 because it'll and force all existing users (Including me :smile: ) to upgrade to Django 3.1.

The goal should always be to avoid as many breaking changes as possible. Older versions of Python/Django should be supported until they're officially out-of-date.

That being said, I'll drop support for Django 2.0 and Python3.5

**Comment by Natureshadow** [comment]
That's why you should make a new major version 3.0, and keep 2.x in maintenance with the old JSONField, backporting bugfixes to it ;). There comes a day where you must upgrae away from Django <3.1.

**Comment by danidee10** [comment]
I found a way to do this with [django-jsonfield-backport](https://github.com/laymonage/django-jsonfield-backport)

Just like the name suggests, it's a backport of the new cross-DB `JSONField` functionality to Django < 3.1 (down to 2.2). The great part is that it was created by one of the co-authors of Django's `JSONField` so it's compatible with standard django and new features will be backported until Django 2.2 becomes outdated.
