### ISSUE TITLE
Questionnable usefulness of context processor

### ISSUE THREAD

**Issue by Natureshadow** [danidee10/django-notifs#40]
The context processor in `notifivcations.notifications.notifications`, besides being named interestingly, is of questionnable use in my opinion.

As the current user is injected into template context by default, except if a project diverts from the stnadard behaviour of having `RequestContext`, injecting one attribute of the user again is not really useful. Templates should simply use `user.notifications`.

**Comment by danidee10** [comment]
Totally agree. It's a relic of the old code
