### ISSUE TITLE
what is sender?

### ISSUE THREAD

**Issue by practicuser** [danidee10/django-notifs#9]

**Comment by david-pili** [comment]
I'd also like some clarification on this. 

notify.send(
            sender=self.__class__,**notif_args, channels=['websocket']
        )

What is sender in this context?

**Comment by danidee10** [comment]
Hi @david-pili and @practicuser `sender` is an argument for Django's `Signal.send` method https://docs.djangoproject.com/en/2.1/topics/signals/#django.dispatch.Signal.send

It's nothing special :smile:

**Comment by david-pili** [comment]
Thank you! I appreciate the response.

**Comment by vino-jasuba** [comment]
Hi @danidee10 , can this package be used with DRF out of the box. If not, what do I need to change to make it work?

**Comment by danidee10** [comment]
Hi @vino-jasuba You should be able to use it with any package. (It's not tied to any Django API Framework). What problems are you having exactly? Please open a new issue.

Sorry for the late response.
